### ISSUE TITLE
Replace Travis with Github Actions

### ISSUE THREAD

**Issue by nocalla** [bank2ynab/bank2ynab#309]
**Other feature request**

**Is your feature request related to a problem? Please describe.**
Github Actions are more tightly integrated into Github and offer some interesting workflow options. 

**Describe the solution you'd like**
I think we should migrate our Travis testing into Github Actions.

**Describe alternatives you've considered**
We could leave Travis running on his own, but the fewer moving parts this project has, the better.

**Additional context**
#307 and branch #308

**Comment by nocalla** [comment]
Current Travis .yml file, for reference. 

```
language: python
python:
  - "nightly"
  - "3.8"
  - "3.7"
  - "3.7-dev" # 3.7 development branch
  - "3.6-dev" # 3.6 development branch
  - "3.6"
  - "3.5-dev" # 3.5 development branch
  - "3.5"
  - "3.4"
# install what's needed to run tests
install:
  - pip install flake8
  - pip install coverage
  - pip install codecov
# command to run tests
script:
  - python -m unittest discover -v
  - python bank2ynab.py
  - flake8
  - coverage run bank2ynab.py
after_success:
  - codecov
  - coverage report
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/23be690947c65bd7a84b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
```

**Comment by nocalla** [comment]
My initial Travis-replacement. Current issues - I need to make the code coverage sections work, haven't implemented webhooks or badge updating.

I think separating linting and format-fixing into a separate file would be wise, as linting doesn't need to be done for every individual instance in the operating system/Python version matrix.

```
name: Python testing

on:
    pull_request:
        branches:
        - master
        - develop

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --statistics
    - name: Test with unittest
      run: |
        python -m unittest discover -v
    - name: Code coverage check
      run: |
        echo "Temporarily disabled."
        #pip install coverage
        #pip install codecov
        #codecov
        #coverage report
```
